apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: talend-registry
  containers:
    - name: talend-builder-base
      image: artifactory.datapwn.com/tlnd-docker-dev/talend/common/tsbi/jdk17-builder-base:3.1.9-20230228074507
      tty: true
      command:
        - cat
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/repository
    - name: talend-tsbi-springboot-builder
      image: artifactory.datapwn.com/tlnd-docker-dev/talend/common/tsbi/jdk17-svc-springboot-builder:3.1.9-2.6-20230228074507
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/repository
  volumes:
    - name: m2
      hostPath:
        path: /tmp/jenkins/tsbi/m2