apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: talend-registry
  containers:
    - name: talend-jdk8-builder-base
      image: artifactory.datapwn.com/tlnd-docker-dev/talend/common/tsbi/jdk8-builder-base:2.3.0-20200824113419
      tty: true
      command:
        - cat
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/repository
    - name: sonar-scanner
      image: artifactory.datapwn.com/docker-io-remote/sonarsource/sonar-scanner-cli
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "1G"
          cpu: "1"
        limits:
          memory: "2G"
          cpu: "1"
  volumes:
    - name: m2
      hostPath:
        path: /tmp/jenkins/tsbi/m2